version: "3.3"
services:
  job_board:
    build: .
    container_name: job_board
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/job_board/job_board/static
      - media_volume:/job_board/job_board/media
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/job_board/job_board/static
      - media_volume:/job_board/job_board/media
    ports:
      - "80:80"
    depends_on:
      - job_board

  celery:
    build: .
    container_name: celery
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 15G
        reservations:
          memory: 10G
    expose:
      - 5555
    entrypoint: bash -c " rm -rf /tmp/celery*.pid & python -m celery multi start --app=job_board --pidfile=/tmp/%n.pid --logfile=/job_board/logs/celery/%n.log 4 -c 4 -Q:1 dispatch -Q:2 process_item -Q:3 network -c:4 1 -Q:4 celery -E && python -m celery -A job_board beat --pidfile=/tmp/celerybeat.pid -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --detach && python -m celery flower -A job_board --conf=/job_board/settings/flowerconfig.py --address=0.0.0.0"
    links:
      - rabbit
    depends_on:
      - rabbit
      - job_board

  postgres:
    image: postgres:14.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    expose:
      - 5672

volumes:
  postgres_data: null
  static_volume: null
  media_volume: null
